name: angular_tour_of_heroes
description: Tour of Heroes
version: 0.0.1

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  angular_forms: ^2.0.0
  angular_router: ^2.0.0-alpha


dev_dependencies:
  angular_test: ^2.0.0
  build_runner: ^1.7.0
  build_test: ^0.10.8
  build_web_compilers: ^2.3.0
  pageloader: ^3.0.0
  test: ^1.0.0
